// <auto-generated>
//   This file has been automatically added to your project by the "HotAvalonia.Extensions" NuGet package
//   (https://nuget.org/packages/HotAvalonia.Extensions).
//
//   Please see https://github.com/Kira-NT/HotAvalonia for more information.
// </auto-generated>

#region License
// MIT License
//
// Copyright (c) 2023-2025 Kira NT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#endregion

#line hidden
#pragma warning disable
#nullable enable

namespace HotAvalonia
{
    using global::System;
    using global::System.Diagnostics;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.IO;
    using global::System.Reflection;
    using global::System.Runtime.CompilerServices;
    using global::Avalonia;
    using global::Avalonia.Input;

    /// <summary>
    /// Indicates that the decorated method should be called whenever the associated Avalonia control is hot reloaded.
    /// </summary>
    /// <remarks>
    /// This attribute is intended to be applied to parameterless instance methods of Avalonia controls.
    /// When the control is hot reloaded, the method marked with this attribute is executed.
    /// This can be used to refresh or update the control's state in response to hot reload events.
    ///
    /// <br/><br/>
    ///
    /// The method must meet the following requirements:
    /// <list type="bullet">
    ///   <item>It must be an instance method (i.e., not static).</item>
    ///   <item>It must not have any parameters.</item>
    /// </list>
    ///
    /// Example usage:
    /// <code>
    /// [AvaloniaHotReload]
    /// private void Initialize()
    /// {
    ///     // Code to initialize or refresh
    ///     // the control during hot reload.
    /// }
    /// </code>
    /// </remarks>
    [ExcludeFromCodeCoverage]
    [Conditional("HOTAVALONIA_ENABLE")]
    [AttributeUsage(AttributeTargets.Method)]
    internal sealed partial class AvaloniaHotReloadAttribute : Attribute
    {
    }

#if !HOTAVALONIA_EXCLUDE_EXTENSIONS
    /// <summary>
    /// Provides extension methods for enabling and disabling hot reload functionality for Avalonia applications.
    /// </summary>
    [ExcludeFromCodeCoverage]
    internal static partial class AvaloniaHotReloadExtensions
    {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        private static Func<IHotReloadContext> CreateHotReloadContextFactory(Type controlType, string? controlFilePath)
        {
            return new Func<IHotReloadContext>(() =>
            {
                AvaloniaProjectLocator projectLocator = new AvaloniaProjectLocator(GetFileSystem());
                if (!string.IsNullOrEmpty(controlFilePath) && !projectLocator.FileSystem.FileExists(controlFilePath))
                    throw new FileNotFoundException("The corresponding XAML file could not be found.", controlFilePath);

                if (!string.IsNullOrEmpty(controlFilePath))
                    projectLocator.AddHint(controlType, controlFilePath);

                AvaloniaHotReloadConfig config = AvaloniaHotReloadConfig.Default.With(projectLocator: projectLocator);
                return CreateHotReloadContext(config);
            });
        }

        private static Func<IHotReloadContext> CreateHotReloadContextFactory(Func<Assembly, string?>? projectPathResolver)
        {
            return new Func<IHotReloadContext>(() =>
            {
                AvaloniaProjectLocator projectLocator = new AvaloniaProjectLocator(GetFileSystem());
                if ((object?)projectPathResolver != null)
                    projectLocator.AddHint(projectPathResolver);

                AvaloniaHotReloadConfig config = AvaloniaHotReloadConfig.Default.With(projectLocator: projectLocator);
                return CreateHotReloadContext(config);
            });
        }

#if !HOTAVALONIA_USE_CUSTOM_CONTEXT
        private static IHotReloadContext CreateHotReloadContext(AvaloniaHotReloadConfig config)
        {
#if HOTAVALONIA_ENABLE_LITE
            return AvaloniaHotReloadContext.CreateLite(config);
#else
            return AvaloniaHotReloadContext.Create(config);
#endif
        }
#endif

#if !HOTAVALONIA_USE_CUSTOM_FILE_SYSTEM
        private static global::HotAvalonia.IO.IFileSystem GetFileSystem()
        {
#if HOTAVALONIA_USE_REMOTE_FILE_SYSTEM
            return global::HotAvalonia.IO.FileSystem.Connect(global::HotAvalonia.IO.FileSystem.Empty);
#else
            return global::HotAvalonia.IO.FileSystem.Current;
#endif
        }
#endif
#endif

        /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string})"/>
        public static AppBuilder UseHotReload(this AppBuilder builder)
        {
            return UseHotReload(builder, projectPathResolver: null);
        }

        /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        public static AppBuilder UseHotReload(this AppBuilder builder, KeyGesture? gesture)
        {
            return UseHotReload(builder, projectPathResolver: null, gesture);
        }

        /// <summary>
        /// Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance and automatically
        /// registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
        /// </summary>
        /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        public static AppBuilder UseHotReload(this AppBuilder builder, Func<Assembly, string?> projectPathResolver)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(builder, CreateHotReloadContextFactory(projectPathResolver));
#endif
            return builder;
        }

        /// <summary>
        /// Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance.
        /// </summary>
        /// <param name="builder">The app builder instance.</param>
        /// <param name="projectPathResolver">The callback function capable of resolving a project path for a given assembly.</param>
        /// <param name="gesture">
        /// A gesture representing the hotkey that should trigger a hot reload event,
        /// or <c>null</c> if no hotkey should be registered.
        /// </param>
        /// <returns>The app builder instance.</returns>
        public static AppBuilder UseHotReload(this AppBuilder builder, Func<Assembly, string?> projectPathResolver, KeyGesture? gesture)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(builder, CreateHotReloadContextFactory(projectPathResolver), gesture);
#endif
            return builder;
        }

        /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
        /// <inheritdoc cref="UseHotReload(Application, KeyGesture, string)"/>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void UseHotReload(this Application app, [CallerFilePath] string? appFilePath = null)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(app?.GetType(), appFilePath));
#endif
        }

        /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
        /// <param name="appFilePath">The file path of the application's main source file. Optional if the method called within the file of interest.</param>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void UseHotReload(this Application app, KeyGesture? gesture, [CallerFilePath] string? appFilePath = null)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(app?.GetType(), appFilePath), gesture);
#endif
        }

        /// <summary>
        /// Enables hot reload functionality for the given Avalonia application and automatically
        /// registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
        /// </summary>
        /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void UseHotReload(this Application app, Func<Assembly, string?> projectPathResolver)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(projectPathResolver));
#endif
        }

        /// <summary>
        /// Enables hot reload functionality for the given Avalonia application.
        /// </summary>
        /// <param name="app">The Avalonia application instance for which hot reload should be enabled.</param>
        /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void UseHotReload(this Application app, Func<Assembly, string?> projectPathResolver, KeyGesture? gesture)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(projectPathResolver), gesture);
#endif
        }

        /// <inheritdoc cref="UseHotReload(Application, string)"/>
        [Conditional("HOTAVALONIA_ENABLE")]
        [Obsolete("Use 'UseHotReload(Application, string?)' instead.")]
        public static void EnableHotReload(this Application app, [CallerFilePath] string? appFilePath = null)
        {
            UseHotReload(app, appFilePath);
        }

        /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
        [Conditional("HOTAVALONIA_ENABLE")]
        [Obsolete("Use 'UseHotReload(Application, Func<Assembly, string?>)' instead.")]
        public static void EnableHotReload(this Application app, Func<Assembly, string?> projectPathResolver)
        {
            UseHotReload(app, projectPathResolver);
        }

        /// <summary>
        /// Disables hot reload functionality for the given Avalonia application.
        /// </summary>
        /// <param name="app">The Avalonia application instance for which hot reload should be disabled.</param>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void DisableHotReload(this Application app)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Disable(app);
#endif
        }

        /// <summary>
        /// Triggers a hot reload event for the given Avalonia application.
        /// </summary>
        /// <param name="app">The Avalonia application instance for which to trigger a hot reload event.</param>
        [Conditional("HOTAVALONIA_ENABLE")]
        public static void TriggerHotReload(this Application app)
        {
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
            AvaloniaHotReload.Trigger(app);
#endif
        }
    }
#endif
}

#nullable restore
#pragma warning restore
#line default
