// <auto-generated>
//   This file has been automatically added to your project by the "HotAvalonia.Extensions" NuGet package
//   (https://nuget.org/packages/HotAvalonia.Extensions).
//
//   Please see https://github.com/Kira-NT/HotAvalonia for more information.
// </auto-generated>

//#region License
// MIT License
//
// Copyright (c) 2023-2025 Kira NT
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//#endregion

#nowarn FS0044
#nowarn FS3261

namespace HotAvalonia

open System
open System.Diagnostics
open System.Diagnostics.CodeAnalysis
open System.IO
open System.Reflection
open System.Runtime.CompilerServices
open System.Runtime.InteropServices
open Avalonia
open Avalonia.Input

/// <summary>
/// Indicates that the decorated method should be called whenever the associated Avalonia control is hot reloaded.
/// </summary>
/// <remarks>
/// This attribute is intended to be applied to parameterless instance methods of Avalonia controls.
/// When the control is hot reloaded, the method marked with this attribute is executed.
/// This can be used to refresh or update the control's state in response to hot reload events.
///
/// <br/><br/>
///
/// The method must meet the following requirements:
/// <list type="bullet">
///   <item>It must be an instance method (i.e., not static).</item>
///   <item>It must not have any parameters.</item>
/// </list>
///
/// Example usage:
/// <code>
/// [<AvaloniaHotReload>]
/// let private initialize () =
///     // Code to initialize or refresh
///     // the control during hot reload.
///     ()
/// </code>
/// </remarks>
[<ExcludeFromCodeCoverage>]
[<Conditional("HOTAVALONIA_ENABLE")>]
[<AttributeUsage(AttributeTargets.Method)>]
type internal AvaloniaHotReloadAttribute() =
    inherit Attribute()

#if !HOTAVALONIA_EXCLUDE_EXTENSIONS
/// <summary>
/// Provides extension methods for enabling and disabling hot reload functionality for Avalonia applications.
/// </summary>
[<ExcludeFromCodeCoverage>]
[<Extension>]
type internal AvaloniaHotReloadExtensions =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
    [<DebuggerStepThrough>]
    static member private CreateHotReloadContextFactory(controlType: Type, controlFilePath: string) = fun() ->
        let projectLocator = AvaloniaProjectLocator(AvaloniaHotReloadExtensions.GetFileSystem())
        if not (String.IsNullOrEmpty(controlFilePath) || projectLocator.FileSystem.FileExists(controlFilePath)) then
            raise (FileNotFoundException("The corresponding XAML file could not be found.", controlFilePath))

        if not (String.IsNullOrEmpty(controlFilePath)) then
            projectLocator.AddHint(controlType, controlFilePath)

        let config = AvaloniaHotReloadConfig.Default.With(projectLocator = projectLocator)
        AvaloniaHotReloadExtensions.CreateHotReloadContext(config)

    [<DebuggerStepThrough>]
    static member private CreateHotReloadContextFactory(projectPathResolver: Func<Assembly, string | null> | null) = fun() ->
        let projectLocator = AvaloniaProjectLocator(AvaloniaHotReloadExtensions.GetFileSystem())
        match projectPathResolver with
        | null -> ()
        | hint -> projectLocator.AddHint(hint)

        let config = AvaloniaHotReloadConfig.Default.With(projectLocator = projectLocator)
        AvaloniaHotReloadExtensions.CreateHotReloadContext(config)

#if !HOTAVALONIA_USE_CUSTOM_CONTEXT
    [<DebuggerStepThrough>]
    static member private CreateHotReloadContext(config: AvaloniaHotReloadConfig) =
#if HOTAVALONIA_ENABLE_LITE
        AvaloniaHotReloadContext.CreateLite(config)
#else
        AvaloniaHotReloadContext.Create(config)
#endif
#endif

#if !HOTAVALONIA_USE_CUSTOM_FILE_SYSTEM
    [<DebuggerStepThrough>]
    static member private GetFileSystem() =
#if HOTAVALONIA_USE_REMOTE_FILE_SYSTEM
        HotAvalonia.IO.FileSystem.Connect(HotAvalonia.IO.FileSystem.Empty)
#else
        HotAvalonia.IO.FileSystem.Current
#endif
#endif
#endif

    /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string})"/>
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(builder: AppBuilder) =
        AvaloniaHotReloadExtensions.UseHotReload(builder, projectPathResolver = null)

    /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(builder: AppBuilder, gesture: KeyGesture | null) =
        AvaloniaHotReloadExtensions.UseHotReload(builder, projectPathResolver = null, gesture = gesture)

    /// <summary>
    /// Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance and automatically
    /// registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
    /// </summary>
    /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(builder: AppBuilder, projectPathResolver: Func<Assembly, string | null> | null) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(builder, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(projectPathResolver))
#endif
        builder

    /// <summary>
    /// Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance.
    /// </summary>
    /// <param name="builder">The app builder instance.</param>
    /// <param name="projectPathResolver">The callback function capable of resolving a project path for a given assembly.</param>
    /// <param name="gesture">
    /// A gesture representing the hotkey that should trigger a hot reload event,
    /// or <c>null</c> if no hotkey should be registered.
    /// </param>
    /// <returns>The app builder instance.</returns>
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(builder: AppBuilder, projectPathResolver: Func<Assembly, string | null> | null, gesture: KeyGesture | null) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(builder, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(projectPathResolver), gesture)
#endif
        builder

    /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
    /// <inheritdoc cref="UseHotReload(Application, KeyGesture, string)"/>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(app: Application, [<CallerFilePath; Optional; DefaultParameterValue("")>] appFilePath: string) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(app, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(app.GetType(), appFilePath))
#else
        ()
#endif

    /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
    /// <param name="appFilePath">The file path of the application's main source file. Optional if the method called within the file of interest.</param>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(app: Application, gesture: KeyGesture | null, [<CallerFilePath; Optional; DefaultParameterValue("")>] appFilePath: string) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(app, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(app.GetType(), appFilePath), gesture)
#else
        ()
#endif

    /// <summary>
    /// Enables hot reload functionality for the given Avalonia application and automatically
    /// registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
    /// </summary>
    /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(app: Application, projectPathResolver: Func<Assembly, string | null> | null) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(app, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(projectPathResolver))
#else
        ()
#endif

    /// <summary>
    /// Enables hot reload functionality for the given Avalonia application.
    /// </summary>
    /// <param name="app">The Avalonia application instance for which hot reload should be enabled.</param>
    /// <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member UseHotReload(app: Application, projectPathResolver: Func<Assembly, string | null> | null, gesture: KeyGesture | null) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Enable(app, AvaloniaHotReloadExtensions.CreateHotReloadContextFactory(projectPathResolver), gesture)
#else
        ()
#endif

    /// <inheritdoc cref="UseHotReload(Application, string)"/>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    [<Obsolete("Use 'UseHotReload(Application, string?)' instead.")>]
    static member EnableHotReload(app: Application, [<CallerFilePath; Optional; DefaultParameterValue("")>] appFilePath: string) =
        AvaloniaHotReloadExtensions.UseHotReload(app, appFilePath)

    /// <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    [<Obsolete("Use 'UseHotReload(Application, Func<Assembly, string?>)' instead.")>]
    static member EnableHotReload(app: Application, projectPathResolver: Func<Assembly, string | null> | null) =
        AvaloniaHotReloadExtensions.UseHotReload(app, projectPathResolver)

    /// <summary>
    /// Disables hot reload functionality for the given Avalonia application.
    /// </summary>
    /// <param name="app">The Avalonia application instance for which hot reload should be disabled.</param>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member DisableHotReload(app: Application) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Disable(app)
#else
        ()
#endif

    /// <summary>
    /// Triggers a hot reload event for the given Avalonia application.
    /// </summary>
    /// <param name="app">The Avalonia application instance for which to trigger a hot reload event.</param>
    [<Conditional("HOTAVALONIA_ENABLE")>]
    [<DebuggerStepThrough>]
    [<Extension>]
    static member TriggerHotReload(app: Application) =
#if HOTAVALONIA_ENABLE && !HOTAVALONIA_DISABLE
        AvaloniaHotReload.Trigger(app)
#else
        ()
#endif
#endif
