' <auto-generated>
'   This file has been automatically added to your project by the "HotAvalonia.Extensions" NuGet package
'   (https://nuget.org/packages/HotAvalonia.Extensions).
'
'   Please see https://github.com/Kira-NT/HotAvalonia for more information.
' </auto-generated>

#Region "License"
' MIT License
'
' Copyright (c) 2023-2026 Kira NT
'
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
'
' The above copyright notice and this permission notice shall be included in all
' copies or substantial portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
' SOFTWARE.
#End Region

#Disable Warning

Imports System
Imports System.Diagnostics
Imports System.Diagnostics.CodeAnalysis
Imports System.IO
Imports System.Reflection
Imports System.Runtime.CompilerServices
Imports Avalonia
Imports Avalonia.Input

Namespace Global.HotAvalonia
    ''' <summary>
    ''' Indicates that the decorated method should be called whenever the associated Avalonia control is hot reloaded.
    ''' </summary>
    ''' <remarks>
    ''' This attribute is intended to be applied to parameterless instance methods of Avalonia controls.
    ''' When the control is hot reloaded, the method marked with this attribute is executed.
    ''' This can be used to refresh or update the control's state in response to hot reload events.
    '''
    ''' <br/><br/>
    '''
    ''' The method must meet the following requirements:
    ''' <list type="bullet">
    '''   <item>It must be an instance method (i.e., not static).</item>
    '''   <item>It must not have any parameters.</item>
    ''' </list>
    '''
    ''' Example usage:
    ''' <code>
    ''' <AvaloniaHotReload>
    ''' Private Sub Initialize()
    '''     ' Code to initialize or refresh
    '''     ' the control during hot reload.
    ''' End Sub
    ''' </code>
    ''' </remarks>
    <ExcludeFromCodeCoverage>
    <Conditional("HOTAVALONIA_ENABLE")>
    <AttributeUsage(AttributeTargets.Method)>
    Friend NotInheritable Partial Class AvaloniaHotReloadAttribute
        Inherits Attribute
    End Class

#If Not HOTAVALONIA_EXCLUDE_EXTENSIONS Then
    ''' <summary>
    ''' Provides extension methods for enabling and disabling hot reload functionality for Avalonia applications.
    ''' </summary>
    <ExcludeFromCodeCoverage>
    Friend Partial Module AvaloniaHotReloadExtensions
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
        <DebuggerStepThrough>
        Private Function CreateHotReloadContextFactory(ByVal controlType As Type, ByVal controlFilePath As String) As Func(Of IHotReloadContext)
            Return Function()
                Dim projectLocator as AvaloniaProjectLocator = New AvaloniaProjectLocator(GetFileSystem())
                If Not String.IsNullOrEmpty(controlFilePath) AndAlso Not projectLocator.FileSystem.FileExists(controlFilePath) Then
                    Throw New FileNotFoundException("The corresponding XAML file could not be found.", controlFilePath)
                End If

                If Not String.IsNullOrEmpty(controlFilePath) Then
                    projectLocator.AddHint(controlType, controlFilePath)
                End If

                Dim config as AvaloniaHotReloadConfig = AvaloniaHotReloadConfig.Default.With(projectLocator:=projectLocator)
                Return CreateHotReloadContext(config)
            End Function
        End Function

        <DebuggerStepThrough>
        Private Function CreateHotReloadContextFactory(ByVal projectPathResolver As Func(Of Assembly, String)) As Func(Of IHotReloadContext)
            Return Function()
                Dim projectLocator as AvaloniaProjectLocator = New AvaloniaProjectLocator(GetFileSystem())
                If projectPathResolver IsNot Nothing
                    projectLocator.AddHint(projectPathResolver)
                End If

                Dim config as AvaloniaHotReloadConfig = AvaloniaHotReloadConfig.Default.With(projectLocator:=projectLocator)
                Return CreateHotReloadContext(config)
            End Function
        End Function

#If Not HOTAVALONIA_USE_CUSTOM_CONTEXT Then
        <DebuggerStepThrough>
        Private Function CreateHotReloadContext(ByVal config As AvaloniaHotReloadConfig) As IHotReloadContext
#If HOTAVALONIA_ENABLE_LITE Then
            Return AvaloniaHotReloadContext.CreateLite(config)
#Else
            Return AvaloniaHotReloadContext.Create(config)
#End If
        End Function
#End If

#If Not HOTAVALONIA_USE_CUSTOM_FILE_SYSTEM Then
        <DebuggerStepThrough>
        Private Function GetFileSystem() As HotAvalonia.IO.IFileSystem
#If HOTAVALONIA_USE_REMOTE_FILE_SYSTEM Then
            Return HotAvalonia.IO.FileSystem.Connect(HotAvalonia.IO.FileSystem.Empty)
#Else
            Return HotAvalonia.IO.FileSystem.Current
#End If
        End Function
#End If
#End If

        ''' <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string})"/>
        <DebuggerStepThrough>
        <Extension>
        Public Function UseHotReload(ByVal builder As AppBuilder) As AppBuilder
            Return UseHotReload(builder, projectPathResolver:=Nothing)
        End Function

        ''' <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        <DebuggerStepThrough>
        <Extension>
        Public Function UseHotReload(ByVal builder As AppBuilder, ByVal gesture As KeyGesture) As AppBuilder
            Return UseHotReload(builder, projectPathResolver:=Nothing, gesture)
        End Function

        ''' <summary>
        ''' Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance and automatically
        ''' registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
        ''' </summary>
        ''' <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        <DebuggerStepThrough>
        <Extension>
        Public Function UseHotReload(ByVal builder As AppBuilder, ByVal projectPathResolver As Func(Of Assembly, String)) As AppBuilder
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(builder, CreateHotReloadContextFactory(projectPathResolver))
#End If
            Return builder
        End Function

        ''' <summary>
        ''' Enables hot reload functionality for the specified <see cref="AppBuilder"/> instance.
        ''' </summary>
        ''' <param name="builder">The app builder instance.</param>
        ''' <param name="projectPathResolver">The callback function capable of resolving a project path for a given assembly.</param>
        ''' <param name="gesture">
        ''' A gesture representing the hotkey that should trigger a hot reload event,
        ''' or <c>null</c> if no hotkey should be registered.
        ''' </param>
        ''' <returns>The app builder instance.</returns>
        <DebuggerStepThrough>
        <Extension>
        Public Function UseHotReload(ByVal builder As AppBuilder, ByVal projectPathResolver As Func(Of Assembly, String), ByVal gesture As KeyGesture) As AppBuilder
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(builder, CreateHotReloadContextFactory(projectPathResolver), gesture)
#End If
            Return builder
        End Function

        ''' <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
        ''' <inheritdoc cref="UseHotReload(Application, KeyGesture, string)"/>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub UseHotReload(ByVal app As Application, <CallerFilePath> Optional ByVal appFilePath As String = Nothing)
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(app?.GetType(), appFilePath))
#End If
        End Sub

        ''' <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
        ''' <param name="appFilePath">The file path of the application's main source file. Optional if the method called within the file of interest.</param>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub UseHotReload(ByVal app As Application, ByVal gesture As KeyGesture, <CallerFilePath> Optional ByVal appFilePath As String = Nothing)
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(app?.GetType(), appFilePath), gesture)
#End If
        End Sub

        ''' <summary>
        ''' Enables hot reload functionality for the given Avalonia application and automatically
        ''' registers a default hotkey to trigger a manual hot reload event (usually <c>Alt+F5</c>).
        ''' </summary>
        ''' <inheritdoc cref="UseHotReload(Application, Func{Assembly, string}, KeyGesture)"/>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub UseHotReload(ByVal app As Application, ByVal projectPathResolver As Func(Of Assembly, String))
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(projectPathResolver))
#End If
        End Sub

        ''' <summary>
        ''' Enables hot reload functionality for the given Avalonia application.
        ''' </summary>
        ''' <param name="app">The Avalonia application instance for which hot reload should be enabled.</param>
        ''' <inheritdoc cref="UseHotReload(AppBuilder, Func{Assembly, string}, KeyGesture)"/>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub UseHotReload(ByVal app As Application, ByVal projectPathResolver As Func(Of Assembly, String), ByVal gesture As KeyGesture)
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Enable(app, CreateHotReloadContextFactory(projectPathResolver), gesture)
#End If
        End Sub

        ''' <inheritdoc cref="UseHotReload(Application, string)"/>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        <Obsolete("Use 'UseHotReload(Application, string?)' instead.")>
        Public Sub EnableHotReload(ByVal app As Application, <CallerFilePath> Optional ByVal appFilePath As String = Nothing)
            UseHotReload(app, appFilePath)
        End Sub

        ''' <inheritdoc cref="UseHotReload(Application, Func{Assembly, string})"/>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        <Obsolete("Use 'UseHotReload(Application, Func<Assembly, string?>)' instead.")>
        Public Sub EnableHotReload(ByVal app As Application, ByVal projectPathResolver As Func(Of Assembly, String))
            UseHotReload(app, projectPathResolver)
        End Sub

        ''' <summary>
        ''' Disables hot reload functionality for the given Avalonia application.
        ''' </summary>
        ''' <param name="app">The Avalonia application instance for which hot reload should be disabled.</param>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub DisableHotReload(ByVal app As Application)
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Disable(app)
#End If
        End Sub

        ''' <summary>
        ''' Triggers a hot reload event for the given Avalonia application.
        ''' </summary>
        ''' <param name="app">The Avalonia application instance for which to trigger a hot reload event.</param>
        <Conditional("HOTAVALONIA_ENABLE")>
        <DebuggerStepThrough>
        <Extension>
        Public Sub TriggerHotReload(ByVal app As Application)
#If HOTAVALONIA_ENABLE AndAlso Not HOTAVALONIA_DISABLE Then
            AvaloniaHotReload.Trigger(app)
#End If
        End Sub
    End Module
#End If
End Namespace

#Enable Warning
